[workspace]
resolver = "3"
members = ["compiler", "parser"]

[workspace.package]
edition = "2024"
authors = ["Ales Tsurko <ales.tsurko@gmail.com"]

[workspace.dependencies]
# inner dependencies
gg-parser = { path = "./parser" }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }

# Don't panic.
string_slice = "warn"
indexing_slicing = "warn"
dbg_macro = "warn"
unwrap_used = "warn"
panic = "warn"
todo = "warn"
unimplemented = "warn"
unreachable = "warn"
get_unwrap = "warn"
unwrap_in_result = "warn"
unchecked_time_subtraction = "warn"
panic_in_result_fn = "warn"

# Don't fail silently.
let_underscore_future = "warn"
let_underscore_must_use = "warn"
unused_result_ok = "warn"
map_err_ignore = "warn"
assertions_on_result_states = "warn"

# Don't do bad async stuff.
await_holding_lock = "warn"
await_holding_refcell_ref = "warn"
if_let_mutex = "warn"
large_futures = "warn"

# Don't do unsafe things with memory.
mem_forget = "warn"
undocumented_unsafe_blocks = "deny"
multiple_unsafe_ops_per_block = "warn"
unnecessary_safety_doc = "warn"
unnecessary_safety_comment = "warn"

# Don't do potentially incorrect things with numbers.
float_cmp = "warn"
float_cmp_const = "warn"
lossy_float_literal = "warn"
cast_sign_loss = "warn"
invalid_upcast_comparisons = "warn"

# Don't do bad things that are easy to avoid.
rc_mutex = "warn"
debug_assert_with_mut_call = "warn"
iter_not_returning_iterator = "warn"
expl_impl_clone_on_copy = "warn"
infallible_try_from = "warn"

# Require intentional lint suppressions.
allow_attributes = "warn"
allow_attributes_without_reason = "warn"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "warn"
missing_docs = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"
bare_urls = "warn"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
