[workspace]
resolver = "3"
members = ["cli", "compiler", "parser"]

[workspace.package]
edition = "2024"
authors = ["Ales Tsurko <ales.tsurko@gmail.com"]

[workspace.dependencies]
# inner dependencies
iowa-parser = { path = "./parser" }

[workspace.lints.clippy]
all = "warn"

[workspace.lints.rust]
missing_docs = "warn"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

