[package]
name = "iowa-parser"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.0"
nom = { version = "8", default-features = false, features = ["alloc"] }
rayon = "1.10"

[lints]
workspace = true
