[package]
name = "iowa-compiler"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iowa-parser = { workspace = true }
cranelift-codegen = "0.118.0"
cranelift-frontend = "0.118.0"
cranelift-module = "0.118.0"
cranelift-jit = "0.118.0"
cranelift-native = "0.118.0"
cranelift-wasm = "0.112.3"
thiserror = "1.0"
cranelift-control = "0.118.0"
target-lexicon = "0.12"

[lints]
workspace = true
